/*
** apple1.h  —  Apple 1 emulator amalgamation
**
** Generated by tools/amalgamate.py.  Do NOT edit directly.
** Source: https://github.com/wordgitet/apple1-emu
**
** Single-file build:
**   cc -DAPPLE1_OMIT_DEBUGGER apple1.c -o apple1
**   cl /DAPPLE1_OMIT_DEBUGGER apple1.c /Fe:apple1.exe
*/
#ifndef APPLE1_H
#define APPLE1_H


/* ======== begin port.h ======== */
#ifndef PORT_H
#define PORT_H

/*
 * C89 / C99 Type Portability Shim
 */
#if defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L
#  include <stdbool.h>
#  include <stdint.h>
#else
#  ifndef uint8_t
     typedef unsigned char uint8_t;
#  endif
#  ifndef uint16_t
     typedef unsigned short uint16_t;
#  endif
#  ifndef uint32_t
     typedef unsigned int uint32_t;
#  endif
#  ifndef uint64_t
     typedef unsigned long long uint64_t;
#  endif
#  ifndef int8_t
     typedef signed char int8_t;
#  endif
#  ifndef int16_t
     typedef signed short int16_t;
#  endif
#  ifndef int32_t
     typedef signed int int32_t;
#  endif
#  ifndef int64_t
     typedef signed long long int64_t;
#  endif
#  ifndef bool
#    define bool int
#    define true 1
#    define false 0
#  endif
#endif

/*
 * Getopt Shim Declaration
 */
extern char *port_optarg;
extern int port_optind;
extern int port_opterr;
extern int port_optopt;

int port_getopt(int argc, char *const argv[], const char *optstring);

/*
 * High-resolution timer and sleep shims
 */
uint64_t port_gettime_ns(void);
void port_sleep_ns(uint64_t ns);

/*
 * Implementations
 */
#ifdef PORT_IMPLEMENT_SHIMS

#include <stdio.h>
#include <string.h>

char *port_optarg = NULL;
int port_optind = 1;
int port_opterr = 1;
int port_optopt = 0;

static int optpos = 1;

int
port_getopt(int argc, char *const argv[], const char *optstring)
{
	char *arg;
	char *optchar;
	int ch;

	port_optarg = NULL;
	if (port_optind >= argc || argv[port_optind] == NULL ||
	    argv[port_optind][0] != '-' || argv[port_optind][1] == '\0') {
		return (-1);
	}

	arg = argv[port_optind];
	ch = arg[optpos];
	optchar = strchr(optstring, ch);

	if (ch == '\0' || optchar == NULL) {
		port_optopt = ch;
		if (port_opterr != 0) {
			fprintf(stderr, "%s: illegal option -- %c\n", argv[0], ch);
		}
		optpos = 1;
		port_optind++;
		return ('?');
	}

	if (optchar[1] == ':') {
		if (arg[optpos + 1] != '\0') {
			port_optarg = &arg[optpos + 1];
		} else if (port_optind + 1 < argc) {
			port_optind++;
			port_optarg = argv[port_optind];
		} else {
			port_optopt = ch;
			if (port_opterr != 0) {
				fprintf(stderr, "%s: option requires an argument -- %c\n", argv[0], ch);
			}
			optpos = 1;
			port_optind++;
			return (optstring[0] == ':' ? ':' : '?');
		}
		optpos = 1;
		port_optind++;
	} else {
		optpos++;
		if (arg[optpos] == '\0') {
			optpos = 1;
			port_optind++;
		}
	}
	return (ch);
}

/*
 * Platform-specific timing implementation
 */
#if defined(_WIN32) || defined(_WIN64)
#  include <windows.h>
uint64_t
port_gettime_ns(void)
{
	LARGE_INTEGER freq;
	LARGE_INTEGER counter;

	QueryPerformanceFrequency(&freq);
	QueryPerformanceCounter(&counter);
	return ((uint64_t)(counter.QuadPart * 1000000000LL / freq.QuadPart));
}

void
port_sleep_ns(uint64_t ns)
{
	Sleep((DWORD)(ns / 1000000ULL));
}

#elif defined(__HAIKU__)
#  include <kernel/OS.h>
uint64_t
port_gettime_ns(void)
{
	return ((uint64_t)system_time() * 1000ULL);
}

void
port_sleep_ns(uint64_t ns)
{
	snooze((bigtime_t)(ns / 1000ULL));
}

#elif defined(__QNXNTO__)
#  include <sys/neutrino.h>
#  include <sys/syspage.h>
uint64_t
port_gettime_ns(void)
{
	uint64_t cycles;

	cycles = ClockCycles();
	return ((uint64_t)(cycles * 1000000000ULL / SYSPAGE_ENTRY(qtime)->cycles_per_sec));
}

void
port_sleep_ns(uint64_t ns)
{
	struct timespec req;

	req.tv_sec = (time_t)(ns / 1000000000ULL);
	req.tv_nsec = (long)(ns % 1000000000ULL);
	nanosleep(&req, NULL);
}

#elif defined(__unix__) || defined(__unix) || defined(__APPLE__) || defined(__linux__) || defined(__FreeBSD__) || defined(__NetBSD__) || defined(__OpenBSD__) || defined(__DragonFly__) || defined(__sun) || defined(__rtems__)
/* Standard POSIX default */
#  ifndef _POSIX_C_SOURCE
#    define _POSIX_C_SOURCE 199309L
#  endif
#  include <time.h>
uint64_t
port_gettime_ns(void)
{
	struct timespec ts;

	if (clock_gettime(CLOCK_MONOTONIC, &ts) == 0) {
		return ((uint64_t)ts.tv_sec * 1000000000ULL + (uint64_t)ts.tv_nsec);
	}
	return (0);
}

void
port_sleep_ns(uint64_t ns)
{
	struct timespec req;

	req.tv_sec = (time_t)(ns / 1000000000ULL);
	req.tv_nsec = (long)(ns % 1000000000ULL);
	nanosleep(&req, NULL);
}
#else
/* Bare-metal / custom RTOS mock fallback */
uint64_t
port_gettime_ns(void)
{
	static uint64_t mock_ticks = 0;
	/* Pretend 1 millisecond passes each check */
	return (mock_ticks += 1000000ULL);
}

void
port_sleep_ns(uint64_t ns)
{
	/* Busy loop fallback */
	volatile uint64_t count;
	for (count = 0; count < ns / 10ULL; count++) {
		/* no-op */
	}
}
#endif

#endif /* PORT_IMPLEMENT_SHIMS */

#endif /* PORT_H */
/* ======== end port.h ======== */

/* ======== begin bus.h ======== */
#ifndef BUS_H
#define BUS_H

#define PIA_BASE      0xD010
#define ROM_BASE      0xFF00
#define RESET_VECTOR  0xFFFC

/* amalgamation: omit #include "port.h" */
#include <stddef.h>

/* Log severity levels */
#define BUS_LOG_INFO  0
#define BUS_LOG_WARN  1
#define BUS_LOG_ERROR 2

/*
 * Route a log message through the bus log callback.
 * Silently dropped when log is NULL (embedded targets with no output).
 */
#define BUS_LOG(bus, lvl, msg) \
    do { \
        if ((bus)->log != NULL) \
            (bus)->log((bus)->log_ctx, (lvl), (msg)); \
    } while (0)

/* Callback fired on every non-dummy bus read and write.
 * addr     - the final (post-alias-resolution) address accessed
 * is_write - true for writes, false for reads
 * val      - the byte written or read */
typedef void (
    *bus_access_cb_t)(void *ctx, uint16_t addr, bool is_write, uint8_t val);

struct pia_6821 {
	uint8_t kbd_data;    /* 0xD010: Keyboard Data */
	uint8_t kbd_control; /* 0xD011: Keyboard Control (Bit 7: Keyboard Strobe) */
	uint8_t dsp_data;    /* 0xD012: Display Data */
	uint8_t dsp_control; /* 0xD013: Display Control (Bit 7: Display Ready) */
};

struct emu_opts {
	bool uncapped;
	bool throttle_pia;
	bool emulate_dram_refresh;
	bool emulate_kbd_bounce;
	bool randomize_cold_boot;
	bool flat_bus;
	bool headless;
};

struct expansion_card {
	const char *name;
	uint16_t base;
	uint16_t mask;
	bool rom_only;

	uint8_t (*read)(void *ctx, uint16_t addr, bool is_dummy);
	void (*write)(void *ctx, uint16_t addr, uint8_t val, bool is_dummy);
	void (*tick)(void *ctx, uint8_t cycles);

	void *ctx;
};

struct bus {
	uint8_t *ram;
	uint32_t ram_size;
	uint8_t rom[256];
	bool rom_loaded;
	struct pia_6821 pia;
	struct emu_opts opts;
	uint8_t last_bus_value;
	struct expansion_card *cards[8];
	int num_cards;
	uint32_t kbd_bounce_cycles; /* remaining bounce window (in calls) */

	/* Optional callback fired on every non-dummy bus access (read or write).
	 * Set to NULL to disable.  Used by the debugger for watchpoints. */
	bus_access_cb_t access_cb;
	void *access_cb_ctx;

	/* Optional log callback.  If NULL, all messages are silently dropped.
	 * Frontends set this to route errors to stderr, a GUI log, or a UART. */
	void (*log)(void *log_ctx, int level, const char *msg);
	void *log_ctx;
};

/* Initialize the memory bus with a configured RAM size and buffer */
bool
bus_init(struct bus *bus, uint8_t *ram_buf, uint32_t ram_size);

/* Clean up */
void
bus_free(struct bus *bus);

/* Load exactly 256-byte ROM image (Woz Monitor) at 0xFF00-0xFFFF */
bool
bus_load_rom(struct bus *bus, const char *rom_path);

/* Load arbitrary binary file into RAM at the specified starting address */
bool
bus_load_bin(struct bus *bus, const char *bin_path, uint16_t address);

/* Load Woz Monitor formatted text file into RAM. Returns true on success.
 * If run_address is not NULL, it will be set to the R (run) address if
 * specified in the file. */
bool
bus_load_wozmon_txt(struct bus *bus,
    const char *txt_path,
    uint16_t *run_address,
    bool *has_run_address);

/* Read a byte from the bus */
uint8_t
bus_read(struct bus *bus, uint16_t address);

/* Write a byte to the bus */
void
bus_write(struct bus *bus, uint16_t address, uint8_t value);

/* Write a byte to the bus with dummy write flag */
void
bus_write_ext(struct bus *bus, uint16_t address, uint8_t value, bool is_dummy);

/* Poll for keyboard input and update the PIA keyboard registers */
void
bus_update_keyboard(struct bus *bus);

/* Reset the PIA to default/boot state */
void
bus_reset(struct bus *bus);

/* Register an expansion card on the bus */
void
bus_add_card(struct bus *bus, struct expansion_card *card);

/* Resolve relative data file paths using CWD and XDG share paths */
void
resolve_data_path(const char *rel_path, char *out_path, size_t max_len);

#endif /* BUS_H */
/* ======== end bus.h ======== */

/* ======== begin cpu.h ======== */
#ifndef CPU_H
#define CPU_H

#include <stdbool.h>
#include <stdint.h>

/* amalgamation: omit #include "bus.h" */

/* 6502 Processor Status Flags */
enum CPU_FLAGS {
	FLAG_CARRY = 1 << 0,	  /* C */
	FLAG_ZERO = 1 << 1,	  /* Z */
	FLAG_INTERRUPT = 1 << 2,  /* I */
	FLAG_DECIMAL = 1 << 3,	  /* D */
	FLAG_BREAK = 1 << 4,	  /* B (push status sets/clears this) */
	FLAG_UNUSED = 1 << 5,	  /* U (always 1) */
	FLAG_OVERFLOW = 1 << 6,	  /* V */
	FLAG_NEGATIVE = 1 << 7,	  /* N */
};

typedef struct {
	uint16_t from;
	uint16_t to;
} pc_edge_t;

struct cpu {
	uint8_t a;   /* Accumulator */
	uint8_t x;   /* X Register */
	uint8_t y;   /* Y Register */
	uint8_t s;   /* Stack Pointer */
	uint8_t p;   /* Status Flags Register */
	uint16_t pc; /* Program Counter */

	struct bus *bus; /* Reference to the system memory bus */

	bool nmi_pending;    /* Edge-sensitive NMI pending status */
	bool irq_pending;    /* Level-sensitive IRQ pending status */
	bool halted;	     /* Set by JAM/KIL opcodes - struct cpu bus is frozen */
	uint8_t last_cycles; /* Cycles taken by the last executed instruction */

	pc_edge_t pc_trace[24];
	int pc_trace_idx;
	uint16_t prev_pc;
	bool prev_pc_valid;
};

/* Initialize the struct cpu with a reference to the memory bus */
void
cpu_init(struct cpu *cpu, struct bus *bus);

/* Perform a 6502 reset sequence */
void
cpu_reset(struct cpu *cpu);

/* Execute a single struct cpu instruction, returning the cycles taken */
uint8_t
cpu_step(struct cpu *cpu);

/* Assert or deassert level-sensitive IRQ interrupt line */
void
cpu_irq(struct cpu *cpu, bool assert);

/* Assert edge-sensitive NMI interrupt line */
void
cpu_nmi(struct cpu *cpu);

#endif /* CPU_H */
/* ======== end cpu.h ======== */

/* ======== begin dbg.h ======== */
#ifndef DBG_H
#define DBG_H

#include <stdbool.h>

/* amalgamation: omit #include "cpu.h" */

#define MAX_BREAKPOINTS 32
#define MAX_WATCHPOINTS 32

typedef enum { WP_READ = 1, WP_WRITE = 2, WP_ACCESS = 3 } wp_type_t;

typedef struct {
	uint16_t addr;
	wp_type_t type;
} watchpoint_t;

typedef struct {
	struct cpu *cpu;
	uint16_t breakpoints[MAX_BREAKPOINTS];
	int num_breakpoints;
	watchpoint_t watchpoints[MAX_WATCHPOINTS];
	int num_watchpoints;
	bool step_mode;
	uint16_t current_instruction_pc;
} debugger_t;

void
dbg_init(debugger_t *dbg, struct cpu *cpu);
void
dbg_add_breakpoint(debugger_t *dbg, uint16_t addr);
void
dbg_remove_breakpoint(debugger_t *dbg, uint16_t addr);
bool
dbg_has_breakpoint(debugger_t *dbg, uint16_t addr);

void
dbg_add_watchpoint(debugger_t *dbg, uint16_t addr, wp_type_t type);
void
dbg_remove_watchpoint(debugger_t *dbg, uint16_t addr);
void
dbg_check_access(void *ctx, uint16_t addr, bool is_write, uint8_t val);

void
dbg_interactive_loop(debugger_t *dbg);
void
dbg_run_command(debugger_t *dbg, const char *cmd_line);

#endif /* DBG_H */
/* ======== end dbg.h ======== */

/* ======== begin disasm.h ======== */
#ifndef DISASM_H
#define DISASM_H

#include <stdint.h>

/* amalgamation: omit #include "bus.h" */

/* Disassembles one 6502 instruction at memory address pc.
 * Writes the human-readable representation into out_str.
 * Returns the number of bytes consumed by the instruction (1, 2, or 3). */
int
cpu_disassemble(struct bus *bus, uint16_t pc, char *out_str);

#endif /* DISASM_H */
/* ======== end disasm.h ======== */

/* ======== begin aci.h ======== */
#ifndef ACI_H
#define ACI_H

#define ACI_CLOCK 1022727

/* amalgamation: omit #include "bus.h" */

/* Create and initialize the ACI cassette interface card */
struct expansion_card *
aci_create(struct bus *bus, const char *rom_path);

/* Load a .aci tape file into the ACI card */
bool
aci_load_tape(struct expansion_card *card, const char *tape_path);

/* Save recorded ACI tape output to a .aci file */
bool
aci_save_tape(struct expansion_card *card, const char *tape_path);

/* Free ACI card resources */
void
aci_free(struct expansion_card *card);

/* Get recorded pulse transition count */
uint32_t
aci_get_recorded_count(struct expansion_card *card);

#endif /* ACI_H */
/* ======== end aci.h ======== */

/* ======== begin krusader.h ======== */
#ifndef KRUSADER_H
#define KRUSADER_H

#include <stdint.h>

/* amalgamation: omit #include "bus.h" */

/*
 * Internal ROM + state for one Krusader card.
 * Declared here so callers can embed it without malloc.
 */
struct krusader_card {
	uint8_t  rom[4096];
	uint32_t size;
};

/*
 * Create and initialise the Krusader assembler expansion card.
 * bus      - used for BUS_LOG error reporting (must not be NULL).
 * rom_path - path to the Krusader ROM binary (1-4096 bytes).
 * Returns a pointer to the static expansion_card on success, NULL on error.
 * Only one instance is supported at a time.
 */
struct expansion_card *
krusader_create(struct bus *bus, const char *rom_path);

/* Release the Krusader card (marks static slot as free). */
void
krusader_free(struct expansion_card *card);

#endif /* KRUSADER_H */
/* ======== end krusader.h ======== */

/* ======== begin io.h ======== */
#ifndef IO_H
#define IO_H

#include <stdbool.h>
#include <stdint.h>

/* Initialize terminal to raw mode */
void
io_init(void);

/* Restore terminal settings to original state */
void
io_cleanup(void);

/* Check if keyboard input is available (non-blocking) */
bool
io_check_keyboard(void);

/* Read a filtered character from keyboard (auto-uppercases, handles
 * Enter/CR, returns with bit 7 set) */
uint8_t
io_read_keyboard(void);

/* Write character to display (interprets bit 7 and handles carriage returns) */
void
io_write_display(uint8_t value);

/* Set welcome messages to display at the bottom of the alternate screen */
void
io_set_welcome(const char *msg1, const char *msg2);

/* Returns true (once) if Ctrl-R was pressed - caller should call cpu_reset() */
bool
io_reset_pending(void);

/* Check if a keyboard key is currently buffered */
bool
io_has_buffered_key(void);

/* Reset keyboard buffer */
void
io_reset(void);

#endif /* IO_H */
/* ======== end io.h ======== */

/* ======== begin term_apple1.h ======== */
#ifndef TERM_APPLE1_H
#define TERM_APPLE1_H

#include <stdbool.h>
#include <stdint.h>

void
term_init(void);
void
term_shutdown(void);
void
term_write(uint8_t val);
void
term_update(void);
uint8_t
term_poll(void);
void
term_set_welcome(const char *msg1, const char *msg2);
bool
term_reset_pending(void);
/* Blocking SDL config wizard — runs before bus init when no config exists.
 * Displays the config modal fullscreen until the user saves and exits. */
void
term_run_config_wizard(void);

/* Power state — when powered off the CRT goes dark and the struct cpu loop idles. */
bool
term_is_powered(void);

/* Returns true if the emulation is paused. */
bool
term_is_paused(void);

/* Push a single trace line (max 128 chars) into the trace ring buffer.
 * Called by main.c every instruction when tracing is active. */
void
term_trace_push(const char *line);

/* Returns true if a struct cpu step was requested from the GUI debugger. */
bool
term_should_step(void);

/* Returns true if the trace window is currently open. */
bool
term_trace_active(void);

/* Request a single struct cpu step from the GUI debugger. */
void
term_request_step(void);

/* Closes the debugger window if it is open. */
void
term_close_debugger(void);

/* Opens the debugger window if it is closed. */
void
term_open_debugger(void);

#endif // TERM_APPLE1_H
/* ======== end term_apple1.h ======== */

#endif /* APPLE1_H */
