/*
** apple1.h  —  Apple 1 emulator amalgamation
**
** Generated by tools/amalgamate.py.  Do NOT edit directly.
** Source: https://github.com/wordgitet/apple1-emu
**
** Single-file build:
**   cc -DAPPLE1_OMIT_DEBUGGER apple1.c -o apple1
**   cl /DAPPLE1_OMIT_DEBUGGER apple1.c /Fe:apple1.exe
*/
#ifndef APPLE1_H
#define APPLE1_H


/* ======== begin port.h ======== */
#ifndef PORT_H
#define PORT_H

/*
 * port.h -- Apple-1 emulator portability interface
 *
 * This header contains ONLY type definitions, struct declarations,
 * and function prototypes.  It includes exactly one standard header:
 * <stdarg.h>, which is a compiler intrinsic available in all C89
 * environments including freestanding implementations.
 *
 * All implementations live in a single platform-specific port_*.c
 * file selected at compile time (port_posix.c, port_win.c, etc.).
 * Core source files must include only this header, never any system
 * headers directly.
 */
#include <stdarg.h>

/* ================================================================== */
/* Integer type definitions -- zero dependency on <stdint.h>          */
/* ================================================================== */

/*
 * Exact-width types for C89.  Derivation:
 *
 *   char  -- exactly 8 bits on every platform we support.
 *   short -- exactly 16 bits universally.
 *   int   -- 32 bits on ILP32 / LP64 / LLP64.  The ILP64 model
 *             (some old Cray/SPARC variants) is not supported.
 *   long  -- 32 bits on ILP32 / LLP64; 64 bits on LP64.
 */

#ifndef uint8_t
typedef unsigned char  uint8_t;
#endif
#ifndef int8_t
typedef   signed char   int8_t;
#endif
#ifndef uint16_t
typedef unsigned short uint16_t;
#endif
#ifndef int16_t
typedef   signed short  int16_t;
#endif
#ifndef uint32_t
typedef unsigned int   uint32_t;
#endif
#ifndef int32_t
typedef   signed int    int32_t;
#endif

#ifndef UINT8_MAX
#  define UINT8_MAX   255U
#endif
#ifndef UINT16_MAX
#  define UINT16_MAX  65535U
#endif
#ifndef UINT32_MAX
#  define UINT32_MAX  4294967295UL
#endif
#ifndef INT32_MIN
#  define INT32_MIN   (-2147483647 - 1)
#endif
#ifndef INT32_MAX
#  define INT32_MAX   2147483647
#endif

/*
 * bool: C89 has no native boolean type.
 */
#ifndef bool
#  define bool  int
#  define true  1
#  define false 0
#endif

/*
 * port_size_t -- a type large enough to hold the size of any object
 * on the host platform.  We cannot rely on <stddef.h> in freestanding
 * builds, so we derive the type from ABI characteristics:
 *
 *  LP64  (64-bit Linux/macOS/Android, *BSD, AIX):
 *      sizeof(void*) = 8, sizeof(long) = 8 → unsigned long (8 bytes)
 *  LLP64 (64-bit Windows):
 *      sizeof(void*) = 8, sizeof(long) = 4.
 *      C89 has no 'unsigned long long', so we use unsigned long.
 *      Objects in this emulator never exceed 4 GB, so this is safe.
 *  ILP32 (32-bit Unix / embedded / DOS / Haiku):
 *      sizeof(void*) = 4, sizeof(long) = 4 → unsigned long (4 bytes)
 *  16-bit (ELKS / MS-DOS near model):
 *      sizeof(void*) = 2, sizeof(int) = 2 → unsigned int (2 bytes)
 */
#if defined(__x86_64__)   || defined(__aarch64__)  || \
    defined(__mips64)     || defined(__riscv)       || \
    defined(__powerpc64__) || defined(__s390x__)    || \
    defined(__ia64__)     || defined(_M_X64)        || \
    defined(_M_AMD64)     || defined(__LP64__)      || \
    defined(_LP64)
typedef unsigned long port_size_t;
#elif defined(__ELKS__) || \
      (defined(__MSDOS__) || defined(MSDOS) || defined(__dos__))
typedef unsigned int  port_size_t;
#else
typedef unsigned long port_size_t;
#endif

/* ================================================================== */
/* Compiler portability helpers                                        */
/* ================================================================== */

#if defined(__GNUC__) || defined(__clang__)
#  define PORT_UNUSED    __attribute__((unused))
#  define PORT_NORETURN  __attribute__((noreturn))
#else
#  define PORT_UNUSED
#  define PORT_NORETURN
#endif

/* ================================================================== */
/* Memory allocation shims                                            */
/* ================================================================== */

#if defined(APPLE1_ZERO_MALLOC)
#  define port_malloc(sz)        ((void *)0)
#  define port_free(ptr)         ((void)(ptr))
#  define port_realloc(ptr, sz)  ((void *)0)
#elif defined(APPLE1_CUSTOM_MALLOC)
   extern void *port_malloc(port_size_t sz);
   extern void  port_free(void *ptr);
   extern void *port_realloc(void *ptr, port_size_t sz);
#else
   void *port_malloc(port_size_t sz);
   void  port_free(void *ptr);
   void *port_realloc(void *ptr, port_size_t sz);
#endif

char *port_strdup(const char *str);

/* ================================================================== */
/* Memory utility shims                                               */
/* ================================================================== */

void *port_memcpy(void *dst, const void *src, port_size_t n);
void *port_memset(void *dst, int c, port_size_t n);
void *port_memmove(void *dst, const void *src, port_size_t n);
int   port_memcmp(const void *a, const void *b, port_size_t n);

/* ================================================================== */
/* String utility shims                                               */
/* ================================================================== */

port_size_t  port_strlen(const char *s);
char        *port_strncpy(char *dst, const char *src, port_size_t n);
int          port_strcmp(const char *a, const char *b);
int          port_strncmp(const char *a, const char *b, port_size_t n);
char        *port_strchr(const char *s, int c);
char        *port_strstr(const char *hay, const char *needle);
long         port_strtol(const char *s, char **endptr, int base);
unsigned long port_strtoul(const char *s, char **endptr, int base);

/* ================================================================== */
/* Character classification shims                                     */
/* ================================================================== */

int port_isspace(int c);
int port_isdigit(int c);
int port_isxdigit(int c);
int port_isalpha(int c);
int port_isalnum(int c);
int port_toupper(int c);
int port_tolower(int c);

/* ================================================================== */
/* Formatted output shims                                             */
/* ================================================================== */

/*
 * port_snprintf / port_vsnprintf:
 *   Always NUL-terminate buf (even when truncating).
 *   Return value is the number of characters written, not counting the
 *   NUL terminator; negative on error.
 *
 * Supported specifiers: %s %d %i %u %x %X %c %ld %lu %lx %lX %%
 * Flags:                width, '0' (zero-pad), '-' (left-align)
 * No floating point.
 */
int port_snprintf(char *buf, port_size_t n, const char *fmt, ...);
int port_vsnprintf(char *buf, port_size_t n, const char *fmt, va_list ap);

/* ================================================================== */
/* Timing shims                                                       */
/* ================================================================== */

uint32_t port_gettime_us(void);
void     port_sleep_us(uint32_t us);

/* ================================================================== */
/* Terminal I/O shims                                                 */
/* ================================================================== */

/*
 * port_term_raw_enable:  put the controlling terminal into raw/cbreak
 *   mode (no echo, no line buffering, non-blocking read).
 * port_term_raw_disable: restore the terminal to its original mode.
 * port_term_read_char:   read one byte; return -1 if none available.
 * port_term_write_buf:   write n bytes to the terminal output.
 */
void port_term_raw_enable(void);
void port_term_raw_disable(void);
int  port_term_read_char(void);
void port_term_write_buf(const char *buf, port_size_t n);

/*
 * port_term_read_line: read a line of input into buf (up to size-1
 * characters), appending a NUL terminator.  Returns buf on success,
 * NULL on end-of-input / error.  Blocks until a newline or EOF.
 */
char *port_term_read_line(char *buf, port_size_t size);

/* ================================================================== */
/* Signal handling shim                                               */
/* ================================================================== */

/*
 * port_sig_flag: an integer that the signal handler sets to 1 on
 * SIGINT (Ctrl-C) or the platform equivalent.  Must be volatile to
 * prevent the compiler from caching its value in a register.
 */
typedef volatile int port_sig_flag;

/*
 * port_signal_setup: install a handler so that SIGINT increments
 * *flag.  Called once at startup before the main emulation loop.
 */
void port_signal_setup(port_sig_flag *flag);

/*
 * port_signal_quit: platform-independent Ctrl-C / quit request.
 * Sets the flag registered by port_signal_setup (if any).
 * term_poll calls this when the user presses Ctrl-C.
 */
void port_signal_quit(void);

/* ================================================================== */
/* Process exit shim                                                  */
/* ================================================================== */

PORT_NORETURN void port_exit(int code);

/* ================================================================== */
/* Command-line argument parsing shims                                */
/* ================================================================== */

extern char *port_optarg;
extern int   port_optind;
extern int   port_opterr;
extern int   port_optopt;

int port_getopt(int argc, char *const argv[], const char *optstring);

/* ================================================================== */
/* Pseudo-random number generator shims                               */
/* ================================================================== */

uint32_t port_rand(void);
void     port_srand(uint32_t seed);

/* ================================================================== */
/* Virtual File System (VFS)                                          */
/* ================================================================== */

/*
 * The VFS abstraction decouples all file operations from the host OS.
 * Core emulator code never calls fopen/fread/fclose/fseek/ftell
 * directly; it calls through the function pointers in port_vfs_default.
 *
 * To embed the emulator on a system with no file system (bare-metal,
 * ROM-only), replace port_vfs_default with a custom struct port_vfs
 * before calling any bus or ACI initialisation functions.
 *
 * Design mirrors SQLite's sqlite3_vfs: a vtable of function pointers
 * behind a single global pointer that host code can swap out.
 */

/*
 * VFS abstraction.  All file operations go through this vtable so the
 * emulator core never touches fopen/fread/fclose directly.
 *
 * Mirrors SQLite's sqlite3_vfs design: swap g_port_vfs before any
 * bus/ACI init to use a custom filesystem (ROM, EEPROM, RAM-disk …).
 */

#define PORT_VFS_READ  0
#define PORT_VFS_WRITE 1

#define PORT_VFS_SEEK_SET 0
#define PORT_VFS_SEEK_CUR 1
#define PORT_VFS_SEEK_END 2

/*
 * port_file_t: opaque file handle returned by port_vfs->open.
 * PORT_FILE_INVALID is the sentinel for a failed open.
 */
typedef void *port_file_t;
#define PORT_FILE_INVALID ((void *)0)

struct port_vfs {
    /*
     * open: open a file.  Returns an opaque handle on success,
     * PORT_FILE_INVALID on failure.
     * flags: PORT_VFS_READ or PORT_VFS_WRITE.
     */
    port_file_t (*open)(const char *path, int flags);

    /* close: release a file handle returned by open. */
    void  (*close)(port_file_t f);

    /*
     * read: read up to sz bytes into buf.  Stores bytes actually
     * read in *nread.  Returns 0 on success (including short reads
     * at EOF), -1 on error.
     */
    int   (*read)(port_file_t f, void *buf, port_size_t sz,
                  port_size_t *nread);

    /*
     * size: return total file size in bytes without altering the
     * current position.  Returns -1 on error.
     */
    long  (*size)(port_file_t f);

    /*
     * seek: reposition the file pointer.  whence is one of
     * PORT_VFS_SEEK_SET / _CUR / _END.  Returns 0 on success, -1
     * on failure.
     */
    int   (*seek)(port_file_t f, long offset, int whence);

    /*
     * write: write sz bytes from buf.  Returns number of bytes
     * written, or -1 on error.
     */
    long  (*write)(port_file_t f, const void *buf, port_size_t sz);

    /*
     * read_line: read one text line into buf (up to size-1 chars),
     * NUL-terminating the result.  Returns 1 if a line was read,
     * 0 at EOF / error.
     */
    int   (*read_line)(port_file_t f, char *buf, port_size_t size);
};

/*
 * g_port_vfs: global VFS pointer.  Platform port files point this at
 * their implementation struct before any file-loading calls are made.
 * Host apps may replace it for custom storage backends.
 *
 * Use the port_vfs_default convenience alias in call sites so that
 * the code reads like:  port_vfs_default.open(path, PORT_VFS_READ)
 */
extern struct port_vfs *g_port_vfs;
#define port_vfs_default (*g_port_vfs)

#endif /* PORT_H */
/* ======== end port.h ======== */

/* ======== begin bus.h ======== */
#ifndef BUS_H
#define BUS_H

#define PIA_BASE      0xD010
#define ROM_BASE      0xFF00
#define RESET_VECTOR  0xFFFC

/* amalgamation: omit #include "port.h" */
#include "apple1limit.h"
#include <stddef.h>

/* Log severity levels */
#define BUS_LOG_INFO  0
#define BUS_LOG_WARN  1
#define BUS_LOG_ERROR 2

/*
 * Route a log message through the bus log callback.
 * Silently dropped when log is NULL (embedded targets with no output).
 */
#define BUS_LOG(bus, lvl, msg) \
    do { \
        if ((bus)->log != NULL) \
            (bus)->log((bus)->log_ctx, (lvl), (msg)); \
    } while (0)

#ifndef APPLE1_OMIT_BUS_ACCESS_CB
/* Callback fired on every non-dummy bus read and write.
 * addr     - the final (post-alias-resolution) address accessed
 * is_write - true for writes, false for reads
 * val      - the byte written or read */
typedef void (
    *bus_access_cb_t)(void *ctx, uint16_t addr, bool is_write, uint8_t val);
#endif

struct pia_6821 {
	uint8_t kbd_data;    /* 0xD010: Keyboard Data */
	uint8_t kbd_control; /* 0xD011: Keyboard Control (Bit 7: Keyboard Strobe) */
	uint8_t dsp_data;    /* 0xD012: Display Data */
	uint8_t dsp_control; /* 0xD013: Display Control (Bit 7: Display Ready) */
};

struct emu_opts {
	bool uncapped;
	bool throttle_pia;
	bool emulate_dram_refresh;
	bool emulate_kbd_bounce;
	bool randomize_cold_boot;
	bool flat_bus;
	bool headless;
};

struct expansion_card {
	const char *name;
	uint16_t base;
	uint16_t mask;
	bool rom_only;

	uint8_t (*read)(void *ctx, uint16_t addr, bool is_dummy);
	void (*write)(void *ctx, uint16_t addr, uint8_t val, bool is_dummy);
	void (*tick)(void *ctx, uint8_t cycles);

	void *ctx;
};

struct bus {
	uint8_t *ram;
	uint32_t ram_size;
	uint8_t rom[256];
	bool rom_loaded;
	struct pia_6821 pia;
	struct emu_opts opts;
	uint8_t last_bus_value;
	struct expansion_card *cards[APPLE1_MAX_CARDS];
	int num_cards;
	uint32_t kbd_bounce_cycles; /* remaining bounce window (in calls) */

#ifndef APPLE1_OMIT_BUS_ACCESS_CB
	/* Optional callback fired on every non-dummy bus access (read or write).
	 * Set to NULL to disable.  Used by the debugger for watchpoints. */
	bus_access_cb_t access_cb;
	void *access_cb_ctx;
#endif

	/* Optional log callback.  If NULL, all messages are silently dropped.
	 * Frontends set this to route errors to stderr, a GUI log, or a UART. */
	void (*log)(void *log_ctx, int level, const char *msg);
	void *log_ctx;
};

/* Initialize the memory bus with a configured RAM size and buffer */
bool
bus_init(struct bus *bus, uint8_t *ram_buf, uint32_t ram_size);

/* Clean up */
void
bus_free(struct bus *bus);

/* Load binary from buffer into RAM at address */
bool
bus_load_bin_buf(struct bus *bus,
    const uint8_t *data, size_t len, uint16_t address);

/* Load Woz Monitor formatted text from a buffer. */
bool
bus_load_wozmon_txt_buf(struct bus *bus,
    const char *text, size_t len,
    uint16_t *run_address, bool *has_run_address);

/* Load exactly 256-byte ROM image (Woz Monitor) at 0xFF00-0xFFFF */
bool
bus_load_rom(struct bus *bus, const char *rom_path);

#ifndef APPLE1_OMIT_DISKIO
/* Load arbitrary binary file into RAM at the specified starting address */
bool
bus_load_bin(struct bus *bus, const char *bin_path, uint16_t address);

/* Load Woz Monitor formatted text file into RAM. Returns true on success.
 * If run_address is not NULL, it will be set to the R (run) address if
 * specified in the file. */
bool
bus_load_wozmon_txt(struct bus *bus,
    const char *txt_path,
    uint16_t *run_address,
    bool *has_run_address);
#endif

/* Read a byte from the bus */
uint8_t
bus_read(struct bus *bus, uint16_t address);

/* Write a byte to the bus */
void
bus_write(struct bus *bus, uint16_t address, uint8_t value);

/* Write a byte to the bus with dummy write flag */
void
bus_write_ext(struct bus *bus, uint16_t address, uint8_t value, bool is_dummy);

/* Poll for keyboard input and update the PIA keyboard registers */
void
bus_update_keyboard(struct bus *bus);

/* Reset the PIA to default/boot state */
void
bus_reset(struct bus *bus);

/* Register an expansion card on the bus */
void
bus_add_card(struct bus *bus, struct expansion_card *card);

/* Resolve relative data file paths using CWD and XDG share paths */
void
resolve_data_path(const char *rel_path, char *out_path, size_t max_len);

#endif /* BUS_H */
/* ======== end bus.h ======== */

/* ======== begin cpu.h ======== */
#ifndef CPU_H
#define CPU_H

/* amalgamation: omit #include "port.h" */

/* amalgamation: omit #include "bus.h" */

/* 6502 Processor Status Flags */
enum CPU_FLAGS {
	FLAG_CARRY = 1 << 0,	  /* C */
	FLAG_ZERO = 1 << 1,	  /* Z */
	FLAG_INTERRUPT = 1 << 2,  /* I */
	FLAG_DECIMAL = 1 << 3,	  /* D */
	FLAG_BREAK = 1 << 4,	  /* B (push status sets/clears this) */
	FLAG_UNUSED = 1 << 5,	  /* U (always 1) */
	FLAG_OVERFLOW = 1 << 6,	  /* V */
	FLAG_NEGATIVE = 1 << 7	  /* N */
};

typedef struct {
	uint16_t from;
	uint16_t to;
} pc_edge_t;

struct cpu {
	uint8_t a;   /* Accumulator */
	uint8_t x;   /* X Register */
	uint8_t y;   /* Y Register */
	uint8_t s;   /* Stack Pointer */
	uint8_t p;   /* Status Flags Register */
	uint16_t pc; /* Program Counter */

	struct bus *bus; /* Reference to the system memory bus */

	bool nmi_pending;    /* Edge-sensitive NMI pending status */
	bool irq_pending;    /* Level-sensitive IRQ pending status */
	bool halted;	     /* Set by JAM/KIL opcodes - struct cpu bus is frozen */
	uint8_t last_cycles; /* Cycles taken by the last executed instruction */

	pc_edge_t pc_trace[24];
	int pc_trace_idx;
	uint16_t prev_pc;
	bool prev_pc_valid;
};

/* Initialize the struct cpu with a reference to the memory bus */
void
cpu_init(struct cpu *cpu, struct bus *bus);

/* Perform a 6502 reset sequence */
void
cpu_reset(struct cpu *cpu);

/* Execute a single struct cpu instruction, returning the cycles taken */
uint8_t
cpu_step(struct cpu *cpu);

/* Assert or deassert level-sensitive IRQ interrupt line */
void
cpu_irq(struct cpu *cpu, bool assert);

/* Assert edge-sensitive NMI interrupt line */
void
cpu_nmi(struct cpu *cpu);

#endif /* CPU_H */
/* ======== end cpu.h ======== */

/* ======== begin dbg.h ======== */
#ifndef DBG_H
#define DBG_H

/* amalgamation: omit #include "port.h" */
#include "apple1limit.h"

/* amalgamation: omit #include "cpu.h" */

typedef enum { WP_READ = 1, WP_WRITE = 2, WP_ACCESS = 3 } wp_type_t;

typedef struct {
	uint16_t addr;
	wp_type_t type;
} watchpoint_t;

typedef void (*dbg_out_cb_t)(void *ctx, const char *msg);

typedef struct {
#ifndef APPLE1_OMIT_DEBUGGER
	struct cpu *cpu;
	uint16_t breakpoints[APPLE1_MAX_BREAKPOINTS];
	int num_breakpoints;
	watchpoint_t watchpoints[APPLE1_MAX_WATCHPOINTS];
	int num_watchpoints;
	bool step_mode;
	uint16_t current_instruction_pc;
	dbg_out_cb_t out;
	void *out_ctx;
#else
	int dummy;
#endif
} debugger_t;

void
dbg_init(debugger_t *dbg, struct cpu *cpu);
void
dbg_add_breakpoint(debugger_t *dbg, uint16_t addr);
void
dbg_remove_breakpoint(debugger_t *dbg, uint16_t addr);
bool
dbg_has_breakpoint(debugger_t *dbg, uint16_t addr);

void
dbg_add_watchpoint(debugger_t *dbg, uint16_t addr, wp_type_t type);
void
dbg_remove_watchpoint(debugger_t *dbg, uint16_t addr);
void
dbg_check_access(void *ctx, uint16_t addr, bool is_write, uint8_t val);

void
dbg_interactive_loop(debugger_t *dbg);
void
dbg_run_command(debugger_t *dbg, const char *cmd_line);

#endif /* DBG_H */
/* ======== end dbg.h ======== */

/* ======== begin disasm.h ======== */
#ifndef DISASM_H
#define DISASM_H

#include "apple1limit.h"

#ifndef APPLE1_OMIT_DISASM

/* amalgamation: omit #include "port.h" */

/* amalgamation: omit #include "bus.h" */

/* Disassembles one 6502 instruction at memory address pc.
 * Writes the human-readable representation into out_str.
 * Returns the number of bytes consumed by the instruction (1, 2, or 3). */
int
cpu_disassemble(struct bus *bus, uint16_t pc, char *out_str);

#endif /* APPLE1_OMIT_DISASM */

#endif /* DISASM_H */
/* ======== end disasm.h ======== */

/* ======== begin aci.h ======== */
#ifndef ACI_H
#define ACI_H

#include "apple1limit.h"
/* amalgamation: omit #include "bus.h" */

#ifndef APPLE1_OMIT_ACI

#define ACI_CLOCK 1022727

/* Create and initialize the ACI cassette interface card */
struct expansion_card *
aci_create(struct bus *bus, const char *rom_path);

/* Load a .aci tape file into the ACI card */
bool
aci_load_tape(struct expansion_card *card, const char *tape_path);

/* Save recorded ACI tape output to a .aci file */
bool
aci_save_tape(struct expansion_card *card, const char *tape_path);

/* Free ACI card resources */
void
aci_free(struct expansion_card *card);

/* Get recorded pulse transition count */
uint32_t
aci_get_recorded_count(struct expansion_card *card);

#endif /* APPLE1_OMIT_ACI */

#endif /* ACI_H */
/* ======== end aci.h ======== */

/* ======== begin krusader.h ======== */
#ifndef KRUSADER_H
#define KRUSADER_H

#include "apple1limit.h"

#ifndef APPLE1_OMIT_KRUSADER

/* amalgamation: omit #include "port.h" */

/* amalgamation: omit #include "bus.h" */

/*
 * Internal ROM + state for one Krusader card.
 * Declared here so callers can embed it without malloc.
 */
struct krusader_card {
	uint8_t  rom[4096];
	uint32_t size;
};

/*
 * Create and initialise the Krusader assembler expansion card.
 * bus      - used for BUS_LOG error reporting (must not be NULL).
 * rom_path - path to the Krusader ROM binary (1-4096 bytes).
 * Returns a pointer to the static expansion_card on success, NULL on error.
 * Only one instance is supported at a time.
 */
struct expansion_card *
krusader_create(struct bus *bus, const char *rom_path);

/* Release the Krusader card (marks static slot as free). */
void
krusader_free(struct expansion_card *card);

#endif /* APPLE1_OMIT_KRUSADER */

#endif /* KRUSADER_H */
/* ======== end krusader.h ======== */

/* ======== begin io.h ======== */
#ifndef IO_H
#define IO_H

/* amalgamation: omit #include "port.h" */

/* Initialize terminal to raw mode */
void
io_init(void);

/* Restore terminal settings to original state */
void
io_cleanup(void);

/* Check if keyboard input is available (non-blocking) */
bool
io_check_keyboard(void);

/* Read a filtered character from keyboard (auto-uppercases, handles
 * Enter/CR, returns with bit 7 set) */
uint8_t
io_read_keyboard(void);

/* Write character to display (interprets bit 7 and handles carriage returns) */
void
io_write_display(uint8_t value);

/* Set welcome messages to display at the bottom of the alternate screen */
void
io_set_welcome(const char *msg1, const char *msg2);

/* Returns true (once) if Ctrl-R was pressed - caller should call cpu_reset() */
bool
io_reset_pending(void);

/* Check if a keyboard key is currently buffered */
bool
io_has_buffered_key(void);

/* Reset keyboard buffer */
void
io_reset(void);

#endif /* IO_H */
/* ======== end io.h ======== */

/* ======== begin term_apple1.h ======== */
#ifndef TERM_APPLE1_H
#define TERM_APPLE1_H

/* amalgamation: omit #include "port.h" */

void
term_init(void);
void
term_shutdown(void);
void
term_write(uint8_t val);
/*
 * Returns true when the display is ready to accept another character.
 * In baud-rate mode this returns false until the inter-character delay
 * has elapsed; the PIA dsp_control bit 7 is driven from this flag so
 * that Wozmon's polling loop works correctly without blocking the CPU.
 */
bool
term_dsp_ready(void);
void
term_update(void);
uint8_t
term_poll(void);
void
term_set_welcome(const char *msg1, const char *msg2);
bool
term_reset_pending(void);
/* Blocking SDL config wizard — runs before bus init when no config exists.
 * Displays the config modal fullscreen until the user saves and exits. */
void
term_run_config_wizard(void);

/* Power state — when powered off the CRT goes dark and the struct cpu loop idles. */
bool
term_is_powered(void);

/* Returns true if the emulation is paused. */
bool
term_is_paused(void);

/* Push a single trace line (max 128 chars) into the trace ring buffer.
 * Called by main.c every instruction when tracing is active. */
void
term_trace_push(const char *line);

/* Returns true if a struct cpu step was requested from the GUI debugger. */
bool
term_should_step(void);

/* Returns true if the trace window is currently open. */
bool
term_trace_active(void);

/* Request a single struct cpu step from the GUI debugger. */
void
term_request_step(void);

/* Closes the debugger window if it is open. */
void
term_close_debugger(void);

/* Opens the debugger window if it is closed. */
void
term_open_debugger(void);

#endif /* TERM_APPLE1_H */
/* ======== end term_apple1.h ======== */

#endif /* APPLE1_H */
