# tools/amalgamate_unixware.awk — UnixWare amalgamation (no Python).
#
# Streams output line-by-line (UnixWare nawk cannot hold ~300 KB strings).
# Preset: port.c + term.c with -DAPPLE1_PORT_POSIX -DAPPLE1_TERM_VT100
# Usage: awk -f tools/amalgamate_unixware.awk

function array_clear(a,    k)
{
	for (k in a)
		delete a[k]
}

function basename(path,    n, parts)
{
	n = split(path, parts, "/")
	return parts[n]
}

function parse_include(line,    i, rest)
{
	if (line !~ /^[ 	]*#[ 	]*include[ 	]*"/)
		return ""
	i = index(line, "\"")
	if (i == 0)
		return ""
	rest = substr(line, i + 1)
	i = index(rest, "\"")
	if (i == 0)
		return ""
	return substr(rest, 1, i - 1)
}

function emit(line, outpath)
{
	print line >> outpath
}

function copy_header(file, outpath,    path, line, inc, base)
{
	path = file
	emit("", outpath)
	emit("/* ======== begin " file " ======== */", outpath)
	while ((getline line < path) > 0) {
		inc = parse_include(line)
		if (inc != "") {
			base = basename(inc)
			if (base in seen) {
				emit("/* amalgamation: omit #include \"" inc "\" */",
				    outpath)
				continue
			}
		}
		emit(line, outpath)
	}
	close(path)
	emit("/* ======== end " file " ======== */", outpath)
}

function copy_source(file, outpath,    path, line, inc, base)
{
	path = file
	emit("", outpath)
	emit("/* ======== begin " file " ======== */", outpath)
	while ((getline line < path) > 0) {
		inc = parse_include(line)
		if (inc != "") {
			base = basename(inc)
			if (base in seen) {
				emit("/* amalgamation: omit #include \"" inc "\" */",
				    outpath)
				continue
			}
			if (base in is_optional) {
				emit("/* amalgamation: omit optional \"" inc "\" */",
				    outpath)
				continue
			}
			if (base in is_internal) {
				if (!(base in seen)) {
					emit("", outpath)
					emit("/* ---- begin " base " ---- */",
					    outpath)
					copy_source(base, outpath)
					emit("/* ---- end " base " ---- */",
					    outpath)
					emit("", outpath)
					seen[base] = 1
				} else {
					emit("/* amalgamation: omit #include \"" inc "\" */",
					    outpath)
				}
				continue
			}
		}
		emit(line, outpath)
	}
	close(path)
	emit("/* ======== end " file " ======== */", outpath)
}

BEGIN {
	split("port.h port_stdarg.h bus.h cpu.h dbg.h disasm.h aci.h " \
	    "krusader.h io.h cli_config.h term_apple1.h", pub, " ")
	n_pub = split("port.h port_stdarg.h bus.h cpu.h dbg.h disasm.h aci.h " \
	    "krusader.h io.h cli_config.h term_apple1.h", pub, " ")
	n_src = split("port.c bus.c cpu.c disasm.c aci.c krusader.c dbg.c " \
	    "io.c cli_config.c term.c main.c", src, " ")
	split("embedded_roms.h font5x7.h stb_image_write.h term_internal.h " \
	    "apple1limit.h port_posix_inc.h port_attrs.h port_stdarg_libc.h " \
	    "port_stdarg_plan9.h apple1limit_checks.h port_path.c port_string.c " \
	    "port_posix.c port_win.c port_msdos.c port_plan9.c port_zephyr.c " \
	    "port_bare.c port_os2.c port_vxworks.c port_vms.c port_tcc_va.c " \
	    "term_ansi.c term_dos.c term_vt100.c term_dumb.c", internal, " ")
	split("port_freertos.c port_nspire.c term_nspire.c", optional, " ")
	for (i in optional)
		is_optional[optional[i]] = 1
	for (i in internal)
		is_internal[internal[i]] = 1

	banner_h = "/*\n" \
	    "** apple1.h  —  Apple 1 emulator amalgamation\n" \
	    "**\n" \
	    "** Generated by tools/amalgamate_unixware.awk.  Do NOT edit.\n" \
	    "** UnixWare: cc -DAPPLE1_OMIT_CHARMAP -DAPPLE1_PORT_POSIX " \
	    "-DAPPLE1_TERM_VT100 apple1.c -o apple1\n" \
	    "*/\n"
	banner_c = "/*\n" \
	    "** apple1.c  —  Apple 1 emulator amalgamation\n" \
	    "**\n" \
	    "** Generated by tools/amalgamate_unixware.awk.  Do NOT edit.\n" \
	    "** UnixWare: cc -DAPPLE1_OMIT_CHARMAP -DAPPLE1_PORT_POSIX " \
	    "-DAPPLE1_TERM_VT100 apple1.c -o apple1\n" \
	    "*/\n"

	print banner_h > "apple1.h"
	print "#ifndef APPLE1_H" >> "apple1.h"
	print "#define APPLE1_H" >> "apple1.h"
	print "" >> "apple1.h"

	array_clear(seen)
	for (i = 1; i <= n_pub; i++) {
		copy_header(pub[i], "apple1.h")
		seen[pub[i]] = 1
	}
	print "" >> "apple1.h"
	print "#endif /* APPLE1_H */" >> "apple1.h"
	close("apple1.h")

	print banner_c > "apple1.c"
	print "#include \"apple1.h\"" >> "apple1.c"
	print "" >> "apple1.c"

	array_clear(seen)
	for (i = 1; i <= n_pub; i++)
		seen[pub[i]] = 1
	seen["apple1.h"] = 1
	seen["port.h"] = 1
	for (i = 1; i <= n_src; i++)
		copy_source(src[i], "apple1.c")
	close("apple1.c")

	print "wrote apple1.h"
	print "wrote apple1.c"
}
