# tools/amalgamate_plan9.awk — Plan 9 amalgamation (no Python).
# Preset: port_plan9.c + term_vt100.c
# Usage: awk -f tools/amalgamate_plan9.awk   or   rc tools/amalgamate.rc

BEGIN {
	split("port.h port_stdarg.h bus.h cpu.h dbg.h disasm.h aci.h " \
	    "krusader.h io.h cli_config.h term_apple1.h", pub, " ")
	n_pub = split("port.h port_stdarg.h bus.h cpu.h dbg.h disasm.h aci.h " \
	    "krusader.h io.h cli_config.h term_apple1.h", pub, " ")
	n_src = split("port_string.c port_plan9.c bus.c cpu.c disasm.c aci.c " \
	    "krusader.c dbg.c io.c cli_config.c term_vt100.c main.c", src, " ")
	split("embedded_roms.h font5x7.h stb_image_write.h term_internal.h " \
	    "port_posix_inc.h port_attrs.h port_stdarg_libc.h port_stdarg_plan9.h " \
	    "apple1limit.h apple1limit_checks.h port_path.c port_string.c " \
	    "port_posix.c port_win.c port_msdos.c port_plan9.c port_freertos.c " \
	    "port_zephyr.c port_bare.c port_os2.c port_vxworks.c port_vms.c " \
	    "port_tcc_va.c term_ansi.c term_dos.c term_vt100.c term_dumb.c", internal, " ")
	for (i in internal)
		is_internal[internal[i]] = 1
	for (i = 1; i <= n_pub; i++)
		is_pub[pub[i]] = 1

	banner = "/*\n" \
	    "** %s  —  Apple 1 emulator amalgamation\n" \
	    "**\n" \
	    "** Generated by tools/amalgamate_plan9.awk.  Do NOT edit directly.\n" \
	    "** Source: https://github.com/wordgitet/apple1-emu\n" \
	    "**\n" \
	    "** Plan 9 single-file build:\n" \
	    "**   6c -DAPPLE1_OMIT_CHARMAP -DAPPLE1_PORT_PLAN9 " \
	    "-DAPPLE1_TERM_VT100 apple1.c\n" \
	    "*/\n"

	hout = sprintf(banner, "apple1.h")
	hout = hout "#ifndef APPLE1_H\n#define APPLE1_H\n\n"
	delete seen
	for (i = 1; i <= n_pub; i++) {
		f = pub[i]
		hout = hout "\n/* ======== begin " f " ======== */\n"
		hout = hout read_header(f)
		seen[f] = 1
		hout = hout "/* ======== end " f " ======== */\n"
	}
	hout = hout "\n#endif /* APPLE1_H */\n"

	cout = sprintf(banner, "apple1.c")
	cout = cout "#include \"apple1.h\"\n\n"
	delete seen
	for (i = 1; i <= n_pub; i++)
		seen[pub[i]] = 1
	seen["apple1.h"] = 1
	seen["port.h"] = 1
	for (i = 1; i <= n_src; i++) {
		f = src[i]
		cout = cout "\n/* ======== begin " f " ======== */\n"
		cout = cout embed_source(f)
		cout = cout "/* ======== end " f " ======== */\n"
	}

	printf "%s", hout > "apple1.h"
	printf "%s", cout > "apple1.c"
	close("apple1.h")
	close("apple1.c")
	print "wrote apple1.h (" length(hout) " bytes)"
	print "wrote apple1.c (" length(cout) " bytes)"
}

function basename(path,    n, parts) {
	n = split(path, parts, "/")
	return parts[n]
}

function parse_include(line,    i, rest) {
	if (line !~ /^[ 	]*#[ 	]*include[ 	]*"/)
		return ""
	i = index(line, "\"")
	if (i == 0)
		return ""
	rest = substr(line, i + 1)
	i = index(rest, "\"")
	if (i == 0)
		return ""
	return substr(rest, 1, i - 1)
}

function read_header(file,    path, line, out, inc, base) {
	path = file
	out = ""
	while ((getline line < path) > 0) {
		inc = parse_include(line)
		if (inc != "") {
			base = basename(inc)
			if (base in seen) {
				out = out "/* amalgamation: omit #include \"" inc "\" */\n"
				continue
			}
		}
		out = out line "\n"
	}
	close(path)
	return out
}

function embed_source(file,    path, line, out, inc, base) {
	path = file
	out = ""
	while ((getline line < path) > 0) {
		inc = parse_include(line)
		if (inc != "") {
			base = basename(inc)
			if (base in seen) {
				out = out "/* amalgamation: omit #include \"" inc "\" */\n"
				continue
			}
			if (base in is_internal) {
				if (!(base in seen)) {
					out = out "\n/* ---- begin " base " ---- */\n"
					out = out embed_source(base)
					out = out "/* ---- end " base " ---- */\n\n"
					seen[base] = 1
				} else {
					out = out "/* amalgamation: omit #include \"" inc "\" */\n"
				}
				continue
			}
		}
		out = out line "\n"
	}
	close(path)
	return out
}
