#!/usr/bin/env python3
"""
tools/amalgamate.py  —  Apple 1 emulator amalgamation builder

Produces two files:
  apple1.h   — all public headers concatenated (one-stop include)
  apple1.c   — all translation units in dependency order

Usage:
  python3 tools/amalgamate.py [--srcdir DIR] [--outdir DIR]

Default srcdir is the repository root (parent of tools/).
Default outdir is the repository root.

The amalgamation targets the *portable CLI* build only (no SDL3,
no term_sdl3.c, no term_config.c, no term_debug.c).
Single-file compile example:

  cc -DAPPLE1_OMIT_DEBUGGER apple1.c -o apple1
  cl  /DAPPLE1_OMIT_DEBUGGER apple1.c /Fe:apple1.exe
"""

import argparse
import os
import re
import sys

# ---------------------------------------------------------------------------
# Source order for apple1.c
# ---------------------------------------------------------------------------
# Rules:
#   * List files in dependency order (depended-upon first).
#   * Port shims (port_string.c + one port_*.c) come before core sources.
#   * main.c must be last (it defines main()).
#   * SDL3 / GUI files are excluded.
# ---------------------------------------------------------------------------
PORT_SOURCES = [
    "port.c",
]

C_SOURCES = [
    "bus.c",
    "cpu.c",
    "disasm.c",
    "aci.c",
    "krusader.c",
    "dbg.c",
    "io.c",
    "cli_config.c",
    "term.c",
    "main.c",
]

# Public headers that go into apple1.h (order matters for deps)
PUBLIC_HEADERS = [
    "port.h",
    "port_stdarg.h",
    "bus.h",
    "cpu.h",
    "dbg.h",
    "disasm.h",
    "aci.h",
    "krusader.h",
    "io.h",
    "cli_config.h",
    "term_apple1.h",
]

# Headers that are internal / implementation-detail — NOT re-exported
INTERNAL_HEADERS = {
    "embedded_roms.h",
    "font5x7.h",
    "stb_image_write.h",
    "term_internal.h",
    "term_config.h",
    "term_debug.h",
    "port_string.c",
    "port_posix.c",
    "port_win.c",
    "port_msdos.c",
    "port_plan9.c",
    "port_freertos.c",
    "port_zephyr.c",
    "port_bare.c",
    "port_os2.c",
    "port_elks.c",
    "port_vxworks.c",
    "port_tcc_va.c",
    "term_ansi.c",
    "term_dos.c",
}

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

BANNER = """\
/*
** {name}  —  Apple 1 emulator amalgamation
**
** Generated by tools/amalgamate.py.  Do NOT edit directly.
** Source: https://github.com/wordgitet/apple1-emu
**
** Single-file build:
**   cc -DAPPLE1_OMIT_DEBUGGER apple1.c -o apple1
**   cl /DAPPLE1_OMIT_DEBUGGER apple1.c /Fe:apple1.exe
**   wcl386 -bt=dos -ox -fe=apple1.exe -dAPPLE1_OMIT_CHARMAP apple1.c
*/
"""

# Matches lines like:  #include "foo.h"
LOCAL_INCLUDE_RE = re.compile(r'^\s*#\s*include\s+"([^"]+)"')


def read(path):
    with open(path, encoding="utf-8") as f:
        return f.read()


def embed_file(srcdir, filename, already_included, public_header_set):
    """
    Return the processed text for *filename*.

    Processing rules:
      1. Strip local #include directives for headers that have already been
         inlined (public headers) or are excluded (internal).
      2. Keep all other lines verbatim.
    """
    path = os.path.join(srcdir, filename)
    lines = read(path).splitlines(keepends=True)
    out = []
    for line in lines:
        # Strip redundant local includes
        m = LOCAL_INCLUDE_RE.match(line)
        if m:
            inc = m.group(1)
            # Normalise: strip any leading path component
            inc_base = os.path.basename(inc)
            if inc_base in already_included:
                out.append("/* amalgamation: omit #include \"{inc}\" */\n"
                           .format(inc=inc))
                continue
            if inc_base in INTERNAL_HEADERS:
                # Still need to inline it (once)
                if inc_base not in already_included:
                    inc_path = os.path.join(srcdir, inc_base)
                    if os.path.exists(inc_path):
                        out.append(
                            "\n/* ---- begin {f} ---- */\n".format(f=inc_base))
                        sub_text, _ = embed_file(
                            srcdir, inc_base, already_included,
                            public_header_set)
                        out.append(sub_text)
                        out.append(
                            "/* ---- end {f} ---- */\n\n".format(f=inc_base))
                        already_included.add(inc_base)
                    else:
                        out.append(line)
                else:
                    out.append("/* amalgamation: omit #include \"{inc}\" */\n"
                               .format(inc=inc))
                continue
        out.append(line)
    return "".join(out), already_included


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def build(srcdir, outdir, port_sources, term_src):
    public_header_set = set(PUBLIC_HEADERS)

    # ---- apple1.h -----------------------------------------------------------
    h_parts = [BANNER.format(name="apple1.h")]
    h_parts.append("#ifndef APPLE1_H\n#define APPLE1_H\n\n")

    already_included = set()  # track what we have inlined
    for hdr in PUBLIC_HEADERS:
        path = os.path.join(srcdir, hdr)
        if not os.path.exists(path):
            print("WARNING: header not found: {}".format(path), file=sys.stderr)
            continue
        h_parts.append("\n/* ======== begin {f} ======== */\n".format(f=hdr))
        # Strip the header guard and local includes we've already emitted
        lines = read(path).splitlines(keepends=True)
        for line in lines:
            m = LOCAL_INCLUDE_RE.match(line)
            if m:
                inc_base = os.path.basename(m.group(1))
                if inc_base in already_included:
                    h_parts.append(
                        "/* amalgamation: omit #include \"{h}\" */\n"
                        .format(h=m.group(1)))
                    continue
            h_parts.append(line)
        already_included.add(hdr)
        h_parts.append("/* ======== end {f} ======== */\n".format(f=hdr))

    h_parts.append("\n#endif /* APPLE1_H */\n")

    h_out = os.path.join(outdir, "apple1.h")
    with open(h_out, "w", encoding="utf-8") as f:
        f.write("".join(h_parts))
    print("wrote {}  ({} bytes)".format(h_out, os.path.getsize(h_out)))

    # ---- apple1.c -----------------------------------------------------------
    c_parts = [BANNER.format(name="apple1.c")]
    c_parts.append('#include "apple1.h"\n\n')

    # Mark port.h and all public headers as already inlined so embed_file
    # strips their #include directives from every source file.
    already_included = set(PUBLIC_HEADERS)
    already_included.add("apple1.h")
    already_included.add("port.h")

    c_sources = port_sources + [
        "bus.c",
        "cpu.c",
        "disasm.c",
        "aci.c",
        "krusader.c",
        "dbg.c",
        "io.c",
        term_src,
        "main.c",
    ]

    for src in c_sources:
        path = os.path.join(srcdir, src)
        if not os.path.exists(path):
            print("WARNING: source not found: {}".format(path), file=sys.stderr)
            continue
        c_parts.append(
            "\n/* ======== begin {f} ======== */\n".format(f=src))
        text, already_included = embed_file(
            srcdir, src, already_included, public_header_set)
        c_parts.append(text)
        c_parts.append(
            "/* ======== end {f} ======== */\n".format(f=src))

    c_out = os.path.join(outdir, "apple1.c")
    with open(c_out, "w", encoding="utf-8") as f:
        f.write("".join(c_parts))
    print("wrote {}  ({} bytes)".format(c_out, os.path.getsize(c_out)))


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    default_src = os.path.dirname(here)  # parent of tools/

    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--srcdir", default=default_src,
                    help="Repository root (default: parent of tools/)")
    ap.add_argument("--outdir", default=default_src,
                    help="Output directory (default: same as srcdir)")
    ap.add_argument("--port", default="port.c",
                    help="Platform port file to inline (default: port.c)")
    ap.add_argument("--term", default="term.c",
                    help="Terminal backend to inline (default: term.c)")
    args = ap.parse_args()

    srcdir = os.path.abspath(args.srcdir)
    outdir = os.path.abspath(args.outdir)
    os.makedirs(outdir, exist_ok=True)

    if args.port == "port.c":
        port_sources = ["port.c"]
    else:
        port_sources = ["port_string.c", args.port]
    build(srcdir, outdir, port_sources, args.term)


if __name__ == "__main__":
    main()
